/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevRouteImport } from './routes/dev'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevIndexRouteImport } from './routes/dev.index'
import { Route as DevSpritesRouteImport } from './routes/dev.sprites'
import { Route as DevSpellsRouteImport } from './routes/dev.spells'
import { Route as DevItemsRouteImport } from './routes/dev.items'
import { Route as DevCreaturesRouteImport } from './routes/dev.creatures'
import { Route as DevConfigRouteImport } from './routes/dev.config'

const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevRoute,
} as any)
const DevSpritesRoute = DevSpritesRouteImport.update({
  id: '/sprites',
  path: '/sprites',
  getParentRoute: () => DevRoute,
} as any)
const DevSpellsRoute = DevSpellsRouteImport.update({
  id: '/spells',
  path: '/spells',
  getParentRoute: () => DevRoute,
} as any)
const DevItemsRoute = DevItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => DevRoute,
} as any)
const DevCreaturesRoute = DevCreaturesRouteImport.update({
  id: '/creatures',
  path: '/creatures',
  getParentRoute: () => DevRoute,
} as any)
const DevConfigRoute = DevConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => DevRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dev': typeof DevRouteWithChildren
  '/dev/config': typeof DevConfigRoute
  '/dev/creatures': typeof DevCreaturesRoute
  '/dev/items': typeof DevItemsRoute
  '/dev/spells': typeof DevSpellsRoute
  '/dev/sprites': typeof DevSpritesRoute
  '/dev/': typeof DevIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dev/config': typeof DevConfigRoute
  '/dev/creatures': typeof DevCreaturesRoute
  '/dev/items': typeof DevItemsRoute
  '/dev/spells': typeof DevSpellsRoute
  '/dev/sprites': typeof DevSpritesRoute
  '/dev': typeof DevIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dev': typeof DevRouteWithChildren
  '/dev/config': typeof DevConfigRoute
  '/dev/creatures': typeof DevCreaturesRoute
  '/dev/items': typeof DevItemsRoute
  '/dev/spells': typeof DevSpellsRoute
  '/dev/sprites': typeof DevSpritesRoute
  '/dev/': typeof DevIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dev'
    | '/dev/config'
    | '/dev/creatures'
    | '/dev/items'
    | '/dev/spells'
    | '/dev/sprites'
    | '/dev/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dev/config'
    | '/dev/creatures'
    | '/dev/items'
    | '/dev/spells'
    | '/dev/sprites'
    | '/dev'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dev'
    | '/dev/config'
    | '/dev/creatures'
    | '/dev/items'
    | '/dev/spells'
    | '/dev/sprites'
    | '/dev/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DevRoute: typeof DevRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/sprites': {
      id: '/dev/sprites'
      path: '/sprites'
      fullPath: '/dev/sprites'
      preLoaderRoute: typeof DevSpritesRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/spells': {
      id: '/dev/spells'
      path: '/spells'
      fullPath: '/dev/spells'
      preLoaderRoute: typeof DevSpellsRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/items': {
      id: '/dev/items'
      path: '/items'
      fullPath: '/dev/items'
      preLoaderRoute: typeof DevItemsRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/creatures': {
      id: '/dev/creatures'
      path: '/creatures'
      fullPath: '/dev/creatures'
      preLoaderRoute: typeof DevCreaturesRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/config': {
      id: '/dev/config'
      path: '/config'
      fullPath: '/dev/config'
      preLoaderRoute: typeof DevConfigRouteImport
      parentRoute: typeof DevRoute
    }
  }
}

interface DevRouteChildren {
  DevConfigRoute: typeof DevConfigRoute
  DevCreaturesRoute: typeof DevCreaturesRoute
  DevItemsRoute: typeof DevItemsRoute
  DevSpellsRoute: typeof DevSpellsRoute
  DevSpritesRoute: typeof DevSpritesRoute
  DevIndexRoute: typeof DevIndexRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevConfigRoute: DevConfigRoute,
  DevCreaturesRoute: DevCreaturesRoute,
  DevItemsRoute: DevItemsRoute,
  DevSpellsRoute: DevSpellsRoute,
  DevSpritesRoute: DevSpritesRoute,
  DevIndexRoute: DevIndexRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DevRoute: DevRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
