/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevRouteImport } from './routes/dev'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevIndexRouteImport } from './routes/dev.index'
import { Route as DevOverviewRouteImport } from './routes/dev.overview'
import { Route as AuthenticatedCharactersIndexRouteImport } from './routes/_authenticated/characters.index'
import { Route as AuthenticatedPlayCharacterIdRouteImport } from './routes/_authenticated/play.$characterId'
import { Route as AuthenticatedGameCharacterIdRouteImport } from './routes/_authenticated/game.$characterId'
import { Route as AuthenticatedCharactersNewRouteImport } from './routes/_authenticated/characters.new'

const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevRoute,
} as any)
const DevOverviewRoute = DevOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DevRoute,
} as any)
const AuthenticatedCharactersIndexRoute =
  AuthenticatedCharactersIndexRouteImport.update({
    id: '/characters/',
    path: '/characters/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayCharacterIdRoute =
  AuthenticatedPlayCharacterIdRouteImport.update({
    id: '/play/$characterId',
    path: '/play/$characterId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGameCharacterIdRoute =
  AuthenticatedGameCharacterIdRouteImport.update({
    id: '/game/$characterId',
    path: '/game/$characterId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCharactersNewRoute =
  AuthenticatedCharactersNewRouteImport.update({
    id: '/characters/new',
    path: '/characters/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dev': typeof DevRouteWithChildren
  '/dev/overview': typeof DevOverviewRoute
  '/dev/': typeof DevIndexRoute
  '/characters/new': typeof AuthenticatedCharactersNewRoute
  '/game/$characterId': typeof AuthenticatedGameCharacterIdRoute
  '/play/$characterId': typeof AuthenticatedPlayCharacterIdRoute
  '/characters/': typeof AuthenticatedCharactersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dev/overview': typeof DevOverviewRoute
  '/dev': typeof DevIndexRoute
  '/characters/new': typeof AuthenticatedCharactersNewRoute
  '/game/$characterId': typeof AuthenticatedGameCharacterIdRoute
  '/play/$characterId': typeof AuthenticatedPlayCharacterIdRoute
  '/characters': typeof AuthenticatedCharactersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/dev': typeof DevRouteWithChildren
  '/dev/overview': typeof DevOverviewRoute
  '/dev/': typeof DevIndexRoute
  '/_authenticated/characters/new': typeof AuthenticatedCharactersNewRoute
  '/_authenticated/game/$characterId': typeof AuthenticatedGameCharacterIdRoute
  '/_authenticated/play/$characterId': typeof AuthenticatedPlayCharacterIdRoute
  '/_authenticated/characters/': typeof AuthenticatedCharactersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dev'
    | '/dev/overview'
    | '/dev/'
    | '/characters/new'
    | '/game/$characterId'
    | '/play/$characterId'
    | '/characters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dev/overview'
    | '/dev'
    | '/characters/new'
    | '/game/$characterId'
    | '/play/$characterId'
    | '/characters'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/dev'
    | '/dev/overview'
    | '/dev/'
    | '/_authenticated/characters/new'
    | '/_authenticated/game/$characterId'
    | '/_authenticated/play/$characterId'
    | '/_authenticated/characters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DevRoute: typeof DevRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/overview': {
      id: '/dev/overview'
      path: '/overview'
      fullPath: '/dev/overview'
      preLoaderRoute: typeof DevOverviewRouteImport
      parentRoute: typeof DevRoute
    }
    '/_authenticated/characters/': {
      id: '/_authenticated/characters/'
      path: '/characters'
      fullPath: '/characters/'
      preLoaderRoute: typeof AuthenticatedCharactersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/play/$characterId': {
      id: '/_authenticated/play/$characterId'
      path: '/play/$characterId'
      fullPath: '/play/$characterId'
      preLoaderRoute: typeof AuthenticatedPlayCharacterIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/game/$characterId': {
      id: '/_authenticated/game/$characterId'
      path: '/game/$characterId'
      fullPath: '/game/$characterId'
      preLoaderRoute: typeof AuthenticatedGameCharacterIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/characters/new': {
      id: '/_authenticated/characters/new'
      path: '/characters/new'
      fullPath: '/characters/new'
      preLoaderRoute: typeof AuthenticatedCharactersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCharactersNewRoute: typeof AuthenticatedCharactersNewRoute
  AuthenticatedGameCharacterIdRoute: typeof AuthenticatedGameCharacterIdRoute
  AuthenticatedPlayCharacterIdRoute: typeof AuthenticatedPlayCharacterIdRoute
  AuthenticatedCharactersIndexRoute: typeof AuthenticatedCharactersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCharactersNewRoute: AuthenticatedCharactersNewRoute,
  AuthenticatedGameCharacterIdRoute: AuthenticatedGameCharacterIdRoute,
  AuthenticatedPlayCharacterIdRoute: AuthenticatedPlayCharacterIdRoute,
  AuthenticatedCharactersIndexRoute: AuthenticatedCharactersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface DevRouteChildren {
  DevOverviewRoute: typeof DevOverviewRoute
  DevIndexRoute: typeof DevIndexRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevOverviewRoute: DevOverviewRoute,
  DevIndexRoute: DevIndexRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DevRoute: DevRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
