/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevRouteImport } from './routes/dev'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevIndexRouteImport } from './routes/dev.index'
import { Route as DevVocationsRouteImport } from './routes/dev.vocations'
import { Route as DevSpritesRouteImport } from './routes/dev.sprites'
import { Route as DevSpellsRouteImport } from './routes/dev.spells'
import { Route as DevScriptsRouteImport } from './routes/dev.scripts'
import { Route as DevPalettesRouteImport } from './routes/dev.palettes'
import { Route as DevOverviewRouteImport } from './routes/dev.overview'
import { Route as DevObjectsRouteImport } from './routes/dev.objects'
import { Route as DevNpcsRouteImport } from './routes/dev.npcs'
import { Route as DevMonstersRouteImport } from './routes/dev.monsters'
import { Route as DevMapRouteImport } from './routes/dev.map'
import { Route as DevItemsRouteImport } from './routes/dev.items'
import { Route as DevCreaturesRouteImport } from './routes/dev.creatures'
import { Route as DevConfigRouteImport } from './routes/dev.config'

const DevRoute = DevRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevIndexRoute = DevIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DevRoute,
} as any)
const DevVocationsRoute = DevVocationsRouteImport.update({
  id: '/vocations',
  path: '/vocations',
  getParentRoute: () => DevRoute,
} as any)
const DevSpritesRoute = DevSpritesRouteImport.update({
  id: '/sprites',
  path: '/sprites',
  getParentRoute: () => DevRoute,
} as any)
const DevSpellsRoute = DevSpellsRouteImport.update({
  id: '/spells',
  path: '/spells',
  getParentRoute: () => DevRoute,
} as any)
const DevScriptsRoute = DevScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => DevRoute,
} as any)
const DevPalettesRoute = DevPalettesRouteImport.update({
  id: '/palettes',
  path: '/palettes',
  getParentRoute: () => DevRoute,
} as any)
const DevOverviewRoute = DevOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DevRoute,
} as any)
const DevObjectsRoute = DevObjectsRouteImport.update({
  id: '/objects',
  path: '/objects',
  getParentRoute: () => DevRoute,
} as any)
const DevNpcsRoute = DevNpcsRouteImport.update({
  id: '/npcs',
  path: '/npcs',
  getParentRoute: () => DevRoute,
} as any)
const DevMonstersRoute = DevMonstersRouteImport.update({
  id: '/monsters',
  path: '/monsters',
  getParentRoute: () => DevRoute,
} as any)
const DevMapRoute = DevMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => DevRoute,
} as any)
const DevItemsRoute = DevItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => DevRoute,
} as any)
const DevCreaturesRoute = DevCreaturesRouteImport.update({
  id: '/creatures',
  path: '/creatures',
  getParentRoute: () => DevRoute,
} as any)
const DevConfigRoute = DevConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => DevRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dev': typeof DevRouteWithChildren
  '/dev/config': typeof DevConfigRoute
  '/dev/creatures': typeof DevCreaturesRoute
  '/dev/items': typeof DevItemsRoute
  '/dev/map': typeof DevMapRoute
  '/dev/monsters': typeof DevMonstersRoute
  '/dev/npcs': typeof DevNpcsRoute
  '/dev/objects': typeof DevObjectsRoute
  '/dev/overview': typeof DevOverviewRoute
  '/dev/palettes': typeof DevPalettesRoute
  '/dev/scripts': typeof DevScriptsRoute
  '/dev/spells': typeof DevSpellsRoute
  '/dev/sprites': typeof DevSpritesRoute
  '/dev/vocations': typeof DevVocationsRoute
  '/dev/': typeof DevIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dev/config': typeof DevConfigRoute
  '/dev/creatures': typeof DevCreaturesRoute
  '/dev/items': typeof DevItemsRoute
  '/dev/map': typeof DevMapRoute
  '/dev/monsters': typeof DevMonstersRoute
  '/dev/npcs': typeof DevNpcsRoute
  '/dev/objects': typeof DevObjectsRoute
  '/dev/overview': typeof DevOverviewRoute
  '/dev/palettes': typeof DevPalettesRoute
  '/dev/scripts': typeof DevScriptsRoute
  '/dev/spells': typeof DevSpellsRoute
  '/dev/sprites': typeof DevSpritesRoute
  '/dev/vocations': typeof DevVocationsRoute
  '/dev': typeof DevIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dev': typeof DevRouteWithChildren
  '/dev/config': typeof DevConfigRoute
  '/dev/creatures': typeof DevCreaturesRoute
  '/dev/items': typeof DevItemsRoute
  '/dev/map': typeof DevMapRoute
  '/dev/monsters': typeof DevMonstersRoute
  '/dev/npcs': typeof DevNpcsRoute
  '/dev/objects': typeof DevObjectsRoute
  '/dev/overview': typeof DevOverviewRoute
  '/dev/palettes': typeof DevPalettesRoute
  '/dev/scripts': typeof DevScriptsRoute
  '/dev/spells': typeof DevSpellsRoute
  '/dev/sprites': typeof DevSpritesRoute
  '/dev/vocations': typeof DevVocationsRoute
  '/dev/': typeof DevIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dev'
    | '/dev/config'
    | '/dev/creatures'
    | '/dev/items'
    | '/dev/map'
    | '/dev/monsters'
    | '/dev/npcs'
    | '/dev/objects'
    | '/dev/overview'
    | '/dev/palettes'
    | '/dev/scripts'
    | '/dev/spells'
    | '/dev/sprites'
    | '/dev/vocations'
    | '/dev/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dev/config'
    | '/dev/creatures'
    | '/dev/items'
    | '/dev/map'
    | '/dev/monsters'
    | '/dev/npcs'
    | '/dev/objects'
    | '/dev/overview'
    | '/dev/palettes'
    | '/dev/scripts'
    | '/dev/spells'
    | '/dev/sprites'
    | '/dev/vocations'
    | '/dev'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dev'
    | '/dev/config'
    | '/dev/creatures'
    | '/dev/items'
    | '/dev/map'
    | '/dev/monsters'
    | '/dev/npcs'
    | '/dev/objects'
    | '/dev/overview'
    | '/dev/palettes'
    | '/dev/scripts'
    | '/dev/spells'
    | '/dev/sprites'
    | '/dev/vocations'
    | '/dev/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DevRoute: typeof DevRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/': {
      id: '/dev/'
      path: '/'
      fullPath: '/dev/'
      preLoaderRoute: typeof DevIndexRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/vocations': {
      id: '/dev/vocations'
      path: '/vocations'
      fullPath: '/dev/vocations'
      preLoaderRoute: typeof DevVocationsRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/sprites': {
      id: '/dev/sprites'
      path: '/sprites'
      fullPath: '/dev/sprites'
      preLoaderRoute: typeof DevSpritesRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/spells': {
      id: '/dev/spells'
      path: '/spells'
      fullPath: '/dev/spells'
      preLoaderRoute: typeof DevSpellsRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/scripts': {
      id: '/dev/scripts'
      path: '/scripts'
      fullPath: '/dev/scripts'
      preLoaderRoute: typeof DevScriptsRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/palettes': {
      id: '/dev/palettes'
      path: '/palettes'
      fullPath: '/dev/palettes'
      preLoaderRoute: typeof DevPalettesRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/overview': {
      id: '/dev/overview'
      path: '/overview'
      fullPath: '/dev/overview'
      preLoaderRoute: typeof DevOverviewRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/objects': {
      id: '/dev/objects'
      path: '/objects'
      fullPath: '/dev/objects'
      preLoaderRoute: typeof DevObjectsRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/npcs': {
      id: '/dev/npcs'
      path: '/npcs'
      fullPath: '/dev/npcs'
      preLoaderRoute: typeof DevNpcsRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/monsters': {
      id: '/dev/monsters'
      path: '/monsters'
      fullPath: '/dev/monsters'
      preLoaderRoute: typeof DevMonstersRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/map': {
      id: '/dev/map'
      path: '/map'
      fullPath: '/dev/map'
      preLoaderRoute: typeof DevMapRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/items': {
      id: '/dev/items'
      path: '/items'
      fullPath: '/dev/items'
      preLoaderRoute: typeof DevItemsRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/creatures': {
      id: '/dev/creatures'
      path: '/creatures'
      fullPath: '/dev/creatures'
      preLoaderRoute: typeof DevCreaturesRouteImport
      parentRoute: typeof DevRoute
    }
    '/dev/config': {
      id: '/dev/config'
      path: '/config'
      fullPath: '/dev/config'
      preLoaderRoute: typeof DevConfigRouteImport
      parentRoute: typeof DevRoute
    }
  }
}

interface DevRouteChildren {
  DevConfigRoute: typeof DevConfigRoute
  DevCreaturesRoute: typeof DevCreaturesRoute
  DevItemsRoute: typeof DevItemsRoute
  DevMapRoute: typeof DevMapRoute
  DevMonstersRoute: typeof DevMonstersRoute
  DevNpcsRoute: typeof DevNpcsRoute
  DevObjectsRoute: typeof DevObjectsRoute
  DevOverviewRoute: typeof DevOverviewRoute
  DevPalettesRoute: typeof DevPalettesRoute
  DevScriptsRoute: typeof DevScriptsRoute
  DevSpellsRoute: typeof DevSpellsRoute
  DevSpritesRoute: typeof DevSpritesRoute
  DevVocationsRoute: typeof DevVocationsRoute
  DevIndexRoute: typeof DevIndexRoute
}

const DevRouteChildren: DevRouteChildren = {
  DevConfigRoute: DevConfigRoute,
  DevCreaturesRoute: DevCreaturesRoute,
  DevItemsRoute: DevItemsRoute,
  DevMapRoute: DevMapRoute,
  DevMonstersRoute: DevMonstersRoute,
  DevNpcsRoute: DevNpcsRoute,
  DevObjectsRoute: DevObjectsRoute,
  DevOverviewRoute: DevOverviewRoute,
  DevPalettesRoute: DevPalettesRoute,
  DevScriptsRoute: DevScriptsRoute,
  DevSpellsRoute: DevSpellsRoute,
  DevSpritesRoute: DevSpritesRoute,
  DevVocationsRoute: DevVocationsRoute,
  DevIndexRoute: DevIndexRoute,
}

const DevRouteWithChildren = DevRoute._addFileChildren(DevRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DevRoute: DevRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
