// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hewxrvrqbzkggajgojid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhld3hydnJxYnprZ2dhamdvamlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyMjcxMzYsImV4cCI6MjA3NjgwMzEzNn0.wW32eqMb49QJ5-KGR4WYIcbIkt8NQuyw5qw3hn2PZYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});